# PROJECT: Currency Exchange Rate ETL Pipeline
# This project is designed to extract, transform, and load (ETL) currency exchange rate data from a public API into a MySQL database. 
# The pipeline is structured into three layers: Bronze, Silver, and Gold, each responsible for different stages of data processing.
# The project includes  logging and error handling mechanisms to ensure reliability and maintainability.
# The API used for fetching the currency exchange rate data is "https://frankfurter.dev/" which provides historical exchange rate data for  currencies.
# The historical data is fetched starting from "2000-01-01" to "2026-03-29", and the base currency used for the exchange rates is "USD".
# The ETL pipeline is triggered manually or automatically based on changes in the configuration file.
# The project is implemented in Python and uses libraries such as 
# 1) requests for API calls
# 2) pandas for data manipulation 
# 3) mysql.connector for database interactions
# 4) logging for logging the pipeline execution details.
# The trigger for the pipeline execution is done 3 ways:
# 1) Manual Trigger: The pipeline can be executed manually by running the main.py script
# 2) Config Trigger: The pipeline can be automatically triggered when there are changes in the configuration file (config.json). 
# 3) Schedule Trigger: The pipeline can be scheduled to run at specific intervals (e.g., daily, weekly) using a scheduling tool like cron or Airflow.



# main.py serves as the entry point for the ETL pipeline execution. It is responsible for manually triggering the pipeline and logging the execution details.
import pipeline_execution
from datetime import datetime
import logger
import logging
import loading_config
import time

print(logger.__file__)

if __name__ == "__main__":

    setup_logger_1 = logger.logger("format_1")

    config_data = loading_config.load_config()

    logging.info(f"Pipelie Run By : {config_data["project_runner"]}")
    print(f"Pipelie Run By : {config_data["project_runner"]}")

    logging.info(f"Project Name : {config_data["project_name"]}")
    print(f"Project Name : {config_data["project_name"]}")

    logging.info(f"Time : {datetime.now()}")
    print(f"Time : {datetime.now()}")

    logging.info("--------------------------------------------------------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------------------------------------------------------")
    
    now = datetime.now().strftime('%Y-%m-%d')

    print(f"Manual trigger activated at {now}. Running the ETL pipeline.")
    logging.info(f"Manual trigger activated at {now}. Running the ETL pipeline.")

    clean_data_rows_count, error_data_rows_count = pipeline_execution.pipeline_execution(start_date=config_data["start_date"],end_date="",trigger="manual")

    if clean_data_rows_count is None or error_data_rows_count    is None:
        print("ETL pipeline execution failed .")
        logging.error("ETL pipeline execution failed .")
    else:
        print("cleaned data rows count: ",clean_data_rows_count)
        logging.info(f"cleaned data rows count: {clean_data_rows_count}")

        print("error data rows count: ",error_data_rows_count)
        logging.info(f"error data rows count: {error_data_rows_count}")

        print("Total rows generated by API : ",clean_data_rows_count + error_data_rows_count)
        logging.info(f"Total rows generated by API : {clean_data_rows_count + error_data_rows_count}")

        print("ETL pipeline execution completed successfully.")
        logging.info("ETL pipeline execution completed successfully.")

        print("******************************************** END ********************************************")
        logging.info("******************************************** END ********************************************")