from pathlib import Path
import sys

project_path = Path(__file__).resolve().parent.parent
sys.path.append(str(project_path))


# config_trigger.py is responsible for automatically triggering the ETL pipeline when there are changes in the configuration file (config.json) using a schedule tool cron.. 
# It detects changes in the configuration file, and if any changes are detected, it runs the pipeline_execution function from pipeline_execution.py . 
# It also logs the execution details and updates the hash of the configuration file if the pipeline execution is successful.
# */4 * * * * cd /Users/akshaya1228/ELT_PROJECT_2 && PYTHONPATH=/Users/akshaya1228/ELT_PROJECT_2 /Users/akshaya1228/ELT_PROJECT_2/.venv/bin/python /Users/akshaya1228/ELT_PROJECT_2/triggers/config_trigger.py >> /Users/akshaya1228/ELT_PROJECT_2/cron_config.log 2>&1

import detect_file_changes
import loading_config
import pipeline_execution
from logger import logger
import logging
from datetime import datetime
import header_tail


config_path = "/Users/akshaya1228/ELT_PROJECT_2/config.json"
hash_path = "/Users/akshaya1228/ELT_PROJECT_2/config_hash.txt"


config = loading_config.load_config()

if __name__ == "__main__":
    setup_logger = logger(format = "format_1")


    config_data = loading_config.load_config()

    changed, new_hash = detect_file_changes.detect_file_changes(config_path, hash_path)

    if changed:
        header_tail.head()

        print("Config file has changed. Running the ETL pipeline.")
        logging.info("Config file has changed. Running the ETL pipeline.")

        clean_data_rows_count, error_data_rows_count = pipeline_execution.pipeline_execution(start_date=config_data["start_date"],end_date=config_data["end_date"],trigger="manual")

        if clean_data_rows_count is None or error_data_rows_count is None:
            print("ETL pipeline execution failed. ")
            logging.error("ETL pipeline execution failed.")
        else:
            with open(hash_path, "w") as f:
                f.write(new_hash)
            print("Hash updated successfully.")
            logging.info("Hash updated successfully.")

            print("cleaned data rows count: ",clean_data_rows_count)
            logging.info(f"cleaned data rows count: {clean_data_rows_count}")

            print("error data rows count: ",error_data_rows_count)
            logging.info(f"error data rows count: {error_data_rows_count}")

            print("Total rows generated by API : ",clean_data_rows_count + error_data_rows_count)
            logging.info(f"Total rows generated by API : {clean_data_rows_count + error_data_rows_count}")

            print("ETL pipeline execution completed successfully.")
            logging.info("ETL pipeline execution completed successfully.")

            header_tail.tail()

    else:
        print(f"No config changes. Skipping run. time: {datetime.now()}")
        logging.info(f"No config changes. Skipping run. time: {datetime.now()}")
