from pathlib import Path
import sys

project_path = Path(__file__).resolve().parent.parent
sys.path.append(str(project_path))

# scheduled_trigger.py is responsible for automatically triggering the ETL pipeline at specific intervals (e.g., daily, weekly) using a scheduling tool cron.
# It runs the pipeline_execution function from pipeline_execution.py .
# It also logs the execution details at .
# 0 19 * * * cd /Users/akshaya1228/ELT_PROJECT_2 && PYTHONPATH=/Users/akshaya1228/ELT_PROJECT_2 /Users/akshaya1228/ELT_PROJECT_2/.venv/bin/python /Users/akshaya1228/ELT_PROJECT_2/triggers/scheduled_trigger.py >> /Users/akshaya1228/ELT_PROJECT_2/cron_schedule.log 2>&1

from datetime import datetime
from logger import logger
import pipeline_execution
import logging
import loading_config

if __name__ == "__main__":

    setup_logger = logger("format_1")
    now = datetime.now().strftime('%Y-%m-%d')

    config_data = loading_config.load_config()
    config_data = loading_config.load_config()

    logging.info(f"Pipelie Run By : {config_data["project_runner"]}")
    print(f"Pipelie Run By : {config_data["project_runner"]}")

    logging.info(f"Project Name : {config_data["project_name"]}")
    print(f"Project Name : {config_data["project_name"]}")

    logging.info(f"Time : {datetime.now()}")
    print(f"Time : {datetime.now()}")

    logging.info("--------------------------------------------------------------------------------------------------------------------------")
    print("--------------------------------------------------------------------------------------------------------------------------")


    print(f"Scheduled trigger activated at {now}. Running the ETL pipeline.")
    logging.info(f"Scheduled trigger activated at {now}. Running the ETL pipeline.")

    clean_data_rows_count, error_data_rows_count = pipeline_execution.pipeline_execution(start_date=now,end_date="",trigger="schedule")
    if clean_data_rows_count is None or error_data_rows_count is None:
        print("ETL pipeline execution failed. ")
        logging.error("ETL pipeline execution failed.")
    else:

        print("cleaned data rows count: ",clean_data_rows_count)
        logging.info(f"cleaned data rows count: {clean_data_rows_count}")

        print("error data rows count: ",error_data_rows_count)
        logging.info(f"error data rows count: {error_data_rows_count}")

        print("Total rows generated by API : ",clean_data_rows_count + error_data_rows_count)
        logging.info(f"Total rows generated by API : {clean_data_rows_count + error_data_rows_count}")

        print("ETL pipeline execution completed successfully.")
        logging.info("ETL pipeline execution completed successfully.")

        print("******************************************** END ********************************************")
        logging.info("******************************************** END ********************************************")